apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    backupType: {{ .Values.threefoldVdc.backup | quote }}
  name: tftbscbridge-volume-claim-{{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi