apiVersion: v1
kind: Service
metadata:
  name: {{ include "bsc-bridge-ui.fullname" . }}
  labels:
    {{- include "bsc-bridge-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      name: http
  selector:
    {{- include "bsc-bridge-ui.selectorLabels" . | nindent 4 }}
