---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-bridge-local
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-bridge-local
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
