name: Build and lint the source code

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bridge/stellar
    steps:
      - uses: actions/checkout@v3.5.2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Build
        run: |
          export PATH=/home/runner/go/bin:$PATH
          export GIT_COMMIT=$(git rev-list -1 HEAD) 
          go build -ldflags "-X main.GitCommit=$GIT_COMMIT" .
        env:
          GO111MODULE: on

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: bridge/stellar